server:
  port: 8081
  servlet:
    context-path: /votaciones/
spring:
  datasource:
    url: jdbc:h2:mem:votaciones
    username: sa
    password: password
    driverClassName: org.h2.Driver
    h2:
      console:
        console.enabled: true
        path: /h2-console
        settings.trace: false
        settings.web-allow-others: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


