server:
  port: 8081
  servlet:
    context-path: /votaciones/
spring:

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/votaciones?createDatabaseIfNotExist=true
    username: root
    password: Ct2010**
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true